# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_userphone_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.IntegerField(blank=True, null=True, verbose_name='Population'),
        ),
    ]
