# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_country_population'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='City')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='population')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Country', verbose_name='Country')),
            ],
        ),
    ]
