# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-11 18:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='start_date',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None),
        ),
    ]
